### ISSUE TITLE
Unable to get user profile from GoogleSignIn::Identity class

### ISSUE THREAD

**Issue by tetsuya** [basecamp/google_sign_in#16]
name, avatar_url and locale returns `nil` in `GoogleSignIn::Identity` class.

I noticed these attributes are not included in the payload after going through [lib/google_sign_in/identity.rb](https://github.com/basecamp/google_sign_in/blob/527c9c16d1feedf9ffb67419650cc34c336bce13/lib/google_sign_in/identity.rb).

Do I need to configure something in order to get these values?

```
> google = GoogleSignIn::Identity.new(flash[:google_sign_in_token])
=> #<GoogleSignIn::Identity:0x00007f8acbc34c38
 @payload=
  {"azp"=>"000000000000-example.apps.googleusercontent.com",
   "aud"=>"000000000000-example.apps.googleusercontent.com",
   "sub"=>"000000000000000000000",
   "email"=>"myaddress@gmail.com",
   "email_verified"=>true,
   "at_hash"=>"z1Te3khaFRHeldUn2cXoPg",
   "exp"=>1537010260,
   "iss"=>"accounts.google.com",
   "iat"=>1537006660,
   "cid"=>"000000000000-example.apps.googleusercontent.com"}>

> google.name
=> nil
```

**Comment by georgeclaghorn** [comment]
Google may not provide a name, picture, or locale for any given user. Their [documentation](https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo) doesn’t specify why these claims might not be provided, only that they’re “never guaranteed to be present.” I imagine that they wouldn’t provide a picture, for example, if the user hasn’t uploaded one.

In your application code, expect that you might not receive profile data. At minimum, the following methods should always return usable values:

* `user_id`
* `email_address`
* `email_verified?`
