### ISSUE TITLE
"Unable to retrieve Google public keys" in localhost

### ISSUE THREAD

**Issue by maysam** [basecamp/google_sign_in#20]
I am getting "Unable to retrieve Google public keys" in localhost, but it's working fine in heroku, is it a https thing?

**Comment by georgeclaghorn** [comment]
Is it possible you don’t have a network connection, or you’re filtering outbound network connections somehow, like with [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html)? By default, [`GoogleSignIn::Identity.validator`](https://github.com/basecamp/google_sign_in/blob/80073525fc3f061acaa9264dfe573ecd1f40bf7f/lib/google_sign_in/identity.rb#L8) needs to be able to fetch [Google’s public keys](https://www.googleapis.com/oauth2/v1/certs).

**Comment by maysam** [comment]
you are right 
![image](https://user-images.githubusercontent.com/591033/46593844-f745de80-cadb-11e8-95e7-02967b74f638.png)
