### ISSUE TITLE
Pass the access-token to the proceed_to_url

### ISSUE THREAD

**Issue by seashellski** [basecamp/google_sign_in#23]
Would you be open to a pull-request that enhances the CallbacksController to pass the Google users access-token up to the `proceed_to_url`?

The reason for this is so that the access-token can be cached for validating the state of the Google user between requests to the application.

**Comment by georgeclaghorn** [comment]
I’d be okay with putting the access token in flash data, like the ID token, for the action at the `proceed_to_url` to consume.

**Comment by seashellski** [comment]
Awesome! I'll throw something together for your consideration.

**Comment by jeremy** [comment]
> cached for validating the state of the Google user between requests to the application.

Could you expand on this @seashellski? What state are you validating?

Generally speaking, I'd be comfortable using a Google auth endpoint that only returns an ID token in the first place, limiting us to sign-in purposes by design. Authorization to use other Google APIs would be wonderful to keep out of scope.

**Comment by seashellski** [comment]
@jeremy - the intent is to expose the Google user's access-token to the application so that it can validate whether the Google user is still active, within a Google G Suite organization, between operations.

It's my understanding that this validation can't be done with the Google user ID alone.

This validation is to ensure that the application can automatically terminate the Google user's session if the Google user has been disabled within the Google G Suite organization.

Hopefully that makes sense.

**Comment by seashellski** [comment]
Thanks for the consideration, but I am going to close this.
