### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [basecamp/google_sign_in#39]
Hello,

Looks like there are lot of commits since the last release. Is there a plan for releasing the new version with those changes?

**Comment by joeytheman** [comment]
Any update on this?

**Comment by pisaacs** [comment]
Indeed. Please release new gem or confirm future date/timing. Latest rubygems.org version not aligned with Github's release, and this repo's documentation creates added confusion (e.g., says use rubygems rubygems.org with `gem 'google_sign_in'` but later in documentation references changes not captured in latest rubygem version (such as `flash[:google_sign_in_token]` changed to `flash[:google_sign_in][:id_token]`).  Another option is to update repo's documentation to use the github branch (`gem 'google_sign_in', git: 'https://github.com/basecamp/google_sign_in'`)

**Comment by vizcay** [comment]
No releases since `1.1.2 - October 22, 2018`. Can we start considering this abandomware?

**Comment by ajeygore** [comment]
Given [this](https://m.signalvnoise.com/basecamp-no-longer-requires-google-for-two-factor-authentication/) Can we expect some updates to this gem? If not then please clarify.

**Comment by dhh** [comment]
Pushed the latest as 1.2.0. But yes, this is essentially abandonware otherwise. We will not be working with Google Sign-In at Basecamp going forward. Feel free to fork this gem and continue the work under another name 👍
